# --- GLOBAL SETTINGS ---
data:
  data_to_db: "data_raw"
  db_path: "chroma_db"
  chunk_size: 256
  chunk_overlap: 40

retrieval:
  num_docs: 5
  chunks_per_doc: 2
  active_db: "demo"
  active_embedding: "mini_lm"

generation:
  active_student: "ornl_gpt_oss"

llm:
  gemini_pro:
    provider: "gemini"
    model: "gemini-2.5-flash"
  gemini_flash:
    provider: "gemini"
    model: "gemini-2.0-flash"
  openai_mini:
    provider: "openai"
    model: "gpt-4o-mini" # # https://platform.openai.com/docs/pricing
  groq_llama:
    provider: "groq"
    model: "Llama-3.1-8b-Instant" # # https://console.groq.com/docs/model/llama-3.1-8b-instant # used for paper
  groq_llama2:
    provider: "groq"
    model: "meta-llama/llama-4-scout-17b-16e-instruct" # https://console.groq.com/docs/rate-limits # used for application
  anthropics:
    provider: "anthropic"
    model: "claude-3-haiku-20240307" # https://platform.claude.com/docs/en/about-claude/pricing
  ornl_gpt_oss:
    provider: "ollama"
    model: "gpt-oss:20b"


embeddings:
  mini_lm:
    model: "sentence-transformers/all-MiniLM-L6-v2"
  gte:
    model: "thenlper/gte-small"
  bge:
    model: "BAAI/bge-small-en-v1.5"
  e5:
    model: "intfloat/e5-small-v2"
  snowflake:
    model: "Snowflake/snowflake-arctic-embed-xs"

db:
  mini_lm:
    collection: "all-MiniLM-L6-v2_all_data"
  gte:
    collection: "gte-small_all_data"
  bge:
    collection: "bge-small-en-v1.5_all_data"
  e5:
    collection: "e5-small-v2_all_data"
  snowflake:
    collection: "snowflake-arctic-embed-xs_all_data"
  demo:
    collection: "kdf-demo"